version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
  db:
    image: couchdb:1.6.1
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
    ports:
      - "5984:5984"
